apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: template
  description: A service specification template
  annotations:
      backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
  
