apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: serviceA
  description: A service specification template
				
														  
				
				 
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  consumesApis: ['ems01']
  lifecycle: experimental
  owner:  pr-team-a
  subcomponentOf: keten01
  system: esb
